=== navikt/melosys-schema/schema/fagsaker-sok-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "./sok-fagsaker-schema.json",
  "type": "array",
  "title": "The Root Schema",
  "uniqueItems": true,
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "additionalProperties": false,
    "required": [
      "saksnummer",
      "sammensattNavn",
      "saksstatus",
      "sakstype",
      "opprettetDato",
      "behandlingOversikter"
    ],
    "properties": {
      "saksnummer": {
        "$id": "#/items/properties/saksnummer",
        "type": "string",
        "title": "The Saksnummer Schema",
        "default": "",
        "examples": [
          "4"
        ],
        "pattern": "^(.*)$"
      },
      "sammensattNavn": {
        "$id": "#/items/properties/sammensattNavn",
        "type": "string",
        "title": "The sammensattNavn Schema",
        "default": "",
        "examples": [
          "FÃ¸rstNavn EtterNavn"
        ]
      },
      "saksstatus": {
        "$id": "#/items/properties/saksstatus",
        "title": "The Saksstatus Schema",
        "$ref": "./definitions-schema.json#/definitions/kodeverk"
      },
      "sakstype": {
        "$id": "#/items/properties/sakstype",
        "title": "The Sakstype Schema",
        "$ref": "./definitions-schema.json#/definitions/kodeverk"
      },
      "opprettetDato": {
        "title": "The Opprettetdato Schema",
        "$id": "#/items/properties/opprettetDato",
        "$ref": "./definitions-schema.json#/definitions/dato-tid"
      },
      "behandlingOversikter": {
        "title": "The behandlingOversikter Schema",
        "$id": "#/items/properties/behandlingOversikter",
        "$ref": "./behandlingOversikter-definitions.json#/definitions/behandlingOversikter"
      }
    }
  }
}

=== navikt/melosys-schema/mock_data/fagsaker/sok/fnr-19117220349.json
[
  {
    "saksnummer": "4",
    "sammensattNavn" : "HATT GLITRENDE",
    "opprettetDato": "2017-11-01T12:31:36.123Z",
    "sakstype": {
      "kode": "EU_EOS",
      "term": "EU/EØS"
    },
    "saksstatus" : {
      "kode" : "OPPRETTET",
      "term" : "Saken er opprettet"
    },
    "behandlingOversikter": [
      {
        "behandlingID": 4,
        "opprettetDato": "2017-10-01T12:31:36.123Z",
        "behandlingstype": {
          "kode": "SOEKNAD",
          "term": "Søknad"
        },
        "behandlingsstatus": {
          "kode": "OPPRETTET",
          "term": "Opprettet"
        },
        "soknadsperiode": {
          "fom": "2018-08-01",
          "tom": "2018-12-31"
        },
        "land": [
          "GB"
        ]
      },
      {
        "behandlingID": 10,
        "behandlingsstatus": {
          "kode": "AVVENT_DOK_UTL",
          "term": "Avventer svar fra utenlandsk trygdemyndighet"
        },
        "behandlingstype": {
          "kode": "SOEKNAD",
          "term": "Søknad"
        },
        "land": [
          "PL"
        ],
        "opprettetDato": "2019-04-23T07:48:04.676Z",
        "soknadsperiode": {
          "fom": "2019-02-01",
          "tom": "2020-03-02"
        }
      },
      {
        "behandlingID": 228,
        "behandlingsstatus": {
          "kode": "AVSLUTTET",
          "term": "Behandlingen er avsluttet"
        },
        "behandlingstype": {
          "kode": "UNNTAK_FRA_MEDLEMSKAP",
          "term": "Registrering av unntak"
        },
        "land": null,
        "opprettetDato": "2019-05-08T10:26:45.498Z",
        "soknadsperiode": null
      }
    ]
   }
]

=== navikt/melosys-schema/mock_data/fagsaker-sok/fnr-17117802280.json
[
  {
    "saksnummer": "5",
    "sammensattNavn" : "KAKE ARTIG",
    "opprettetDato": "2017-11-01T12:31:36.123Z",
    "sakstype": {
      "kode": "EU_EOS",
      "term": "EU/EØS"
    },
    "saksstatus" : {
      "kode" : "OPPRETTET",
      "term" : "Saken er opprettet"
    },
    "behandlingOversikter": [
      {
        "behandlingID": 5,
        "opprettetDato": "2017-10-01T12:31:36.123Z",
        "behandlingstype": {
          "kode": "SOEKNAD",
          "term": "Søknad"
        },
        "behandlingsstatus": {
          "kode": "OPPRETTET",
          "term": "Opprettet"
        },
        "soknadsperiode": {
          "fom": "2018-08-01",
          "tom": "2018-12-31"
        },
        "land": [
          "GB"
        ]
      },
      {
        "behandlingID": 9,
        "behandlingsstatus": {
          "kode": "AVSLUTTET",
          "term": "Behandlingen er avsluttet"
        },
        "behandlingstype": {
          "kode": "SOEKNAD",
          "term": "Søknad"
        },
        "land": [
          "NL"
        ],
        "opprettetDato": "2019-04-24T06:29:04.559Z",
        "soknadsperiode": {
          "fom": "2019-04-04",
          "tom": "2020-04-04"
        }
      }
    ]
  }
]
