=== navikt/melosys-schema/schema/sedunderarbeid-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://melosys.nav.no/schemas/sedunderarbeid-schema.json",
  "type": "array",
  "title": "The Root Schema",
  "uniqueItems": true,
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "The Items Schema",
    "additionalProperties": false,
    "required": [
      "bucId",
      "sedId",
      "rinaUrl",
      "opprettetDato",
      "sistOppdatert",
      "sedType",
      "status"
    ],
    "properties": {
      "bucId": {
        "$id": "#/items/properties/bucId",
        "type": "string",
        "title": "The BucId Schema",
        "examples": [
          "30000"
        ],
        "pattern": "^\\S*$"
      },
      "sedId": {
        "$id": "#/items/properties/sedId",
        "type": "string",
        "title": "The SedId Schema",
        "examples": [
          "e25f73dda0b84649899e8ea42cfb25c9"
        ],
        "pattern": "^\\S*$"
      },
      "rinaUrl": {
        "$id": "#/items/properties/rinaUrl",
        "title": "The RinaUrl Schema",
        "$ref": "http://melosys.nav.no/schemas/definitions-schema.json#/definitions/url"
      },
      "opprettetDato": {
        "$id": "#/items/properties/opprettetDato",
        "title": "The OpprettetDato Schema",
        "$ref": "http://melosys.nav.no/schemas/definitions-schema.json#/definitions/dato"
      },
      "sistOppdatert": {
        "$id": "#/items/properties/sistOppdatert",
        "title": "The SistOppdatert Schema",
        "$ref": "http://melosys.nav.no/schemas/definitions-schema.json#/definitions/dato"
      },
      "sedType": {
        "$id": "#/items/properties/sedType",
        "type": "string",
        "title": "The SedType Schema",
        "examples": [
          "A001"
        ],
        "pattern": "^\\S*$"
      },
      "status": {
        "$id": "#/items/properties/status",
        "type": "string",
        "title": "The Status Schema",
        "examples": [
          "new"
        ],
        "pattern": "^\\S*$"
      }
    }
  }
}

=== navikt/melosys-schema/mock_data/eessi/sedunderarbeid/sedunderarbeid.json
[
  {
    "bucId": "40000",
    "sedId": "e25f73dda0b84641231231232cfb25c9",
    "rinaUrl": "http://rina-url.local/",
    "opprettetDato": "2019-05-16",
    "sistOppdatert": "2019-05-16",
    "sedType": "A005",
    "status": "new"
  },
  {
    "bucId": "40001",
    "sedId": "e25f123123b84649899e8ea42cfb25c9",
    "rinaUrl": "http://rina-url.local/",
    "opprettetDato": "2019-04-11",
    "sistOppdatert": "2019-04-12",
    "sedType": "A008",
    "status": "new"
  }
]
